listeners:
    QueryDatabaseListener:
        class: \Joomla\Extension\Workflow\Listener\QueryDatabaseListener
        events:
            onQueryDatabase: addStateConstraint

contenttypes:
    WorkflowState:
        class: \Joomla\Extension\Workflow\ContentType\WorkflowState
